# Calls workflows to validate and pull sources, build the BSP and upload the 
# targets to a common storage area.

on:
  pull_request:
    branches:
      - 'main'

jobs:
  deploy:
    name: deploy
    if: ${{ success() }}
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development
    

